#include "game/tile_data.h"

// 颜色常量（与 cursor.h 一致，避免额外 include）
enum {
	C_RED = 0, C_YELLOW, C_BLUE, C_WHITE, C_GREEN, C_PURPLE, C_GREY, C_LIGHT_GREEN
};

// ============================================================
// 添加新 tile：在此表中加一行即可
// ============================================================
const TileDef g_tile_defs[256] = {
	/*   0 */ { TILE_NONE,    C_WHITE,  "",   "" },

	/*   1 */ { TILE_OBJECT,  C_WHITE,  " ",  "空地" },
	/*   2 */ { TILE_OBJECT,  C_WHITE,  " ",  "墙壁" },
	/*   3 */ { TILE_OBJECT,  C_YELLOW, "〓", "黄门" },
	/*   4 */ { TILE_OBJECT,  C_BLUE,   "〓", "蓝门" },
	/*   5 */ { TILE_OBJECT,  C_RED,    "〓", "红门" },
	/*   6 */ { TILE_OBJECT,  C_WHITE,  " ",  "岩浆" },
	/*   7 */ { TILE_OBJECT,  C_WHITE,  "★", "星星" },
	/*   8 */ { TILE_OBJECT,  C_WHITE,  "〓", "守卫门" },
	/*   9 */ { TILE_OBJECT,  C_WHITE,  "△", "上行楼梯" },
	/*  10 */ { TILE_OBJECT,  C_WHITE,  "▽", "下行楼梯" },
	/*  11 */ { TILE_OBJECT,  C_WHITE,  " ",  "可破墙" },
	/*  12-50 */
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" },

	/*  51 */ { TILE_PROP,    C_YELLOW,      "钥", "黄钥匙" },
	/*  52 */ { TILE_PROP,    C_BLUE,        "钥", "蓝钥匙" },
	/*  53 */ { TILE_PROP,    C_RED,         "钥", "红钥匙" },
	/*  54 */ { TILE_PROP,    C_RED,         "★", "红血瓶" },
	/*  55 */ { TILE_PROP,    C_BLUE,        "★", "蓝血瓶" },
	/*  56 */ { TILE_PROP,    C_RED,         "◆", "红宝石" },
	/*  57 */ { TILE_PROP,    C_BLUE,        "◆", "蓝宝石" },
	/*  58 */ { TILE_PROP,    C_GREY,        "剑", "铁剑" },
	/*  59 */ { TILE_PROP,    C_GREY,        "盾", "铁盾" },
	/*  60 */ { TILE_PROP,    C_WHITE,       "剑", "银剑" },
	/*  61 */ { TILE_PROP,    C_WHITE,       "盾", "银盾" },
	/*  62 */ { TILE_PROP,    C_YELLOW,      "剑", "骑士剑" },
	/*  63 */ { TILE_PROP,    C_YELLOW,      "盾", "骑士盾" },
	/*  64 */ { TILE_PROP,    C_LIGHT_GREEN, "剑", "圣剑" },
	/*  65 */ { TILE_PROP,    C_LIGHT_GREEN, "盾", "圣盾" },
	/*  66 */ { TILE_PROP,    C_RED,         "剑", "神圣剑" },
	/*  67 */ { TILE_PROP,    C_RED,         "盾", "神圣盾" },
	/*  68 */ { TILE_PROP,    C_YELLOW,      "杖", "楼层传送器" },
	/*  69 */ { TILE_PROP,    C_BLUE,        "冰", "冰霜魔法" },
	/*  70 */ { TILE_PROP,    C_RED,         "炸", "炸药" },
	/*  71    */ { TILE_PROP,    C_YELLOW,      "镐", "镐子" },
	/*  72    */ { TILE_NONE,    C_WHITE,       "",   "怪物手册" },
	/*  73    */ { TILE_PROP,    C_YELLOW,      "十", "十字架" },
	/*  74    */ { TILE_PROP,    C_GREEN,       "飞", "中心对称飞行器" },
	/*  75    */ { TILE_PROP,    C_GREEN,       "飞", "下楼飞行器" },
	/*  76    */ { TILE_PROP,    C_GREEN,       "飞", "上楼飞行器" },
	/*  77    */ { TILE_PROP,    C_YELLOW,      "钥", "魔法钥匙" },
	/*  78    */ { TILE_PROP,    C_YELLOW,      "震", "地震卷轴" },
	/*  79    */ { TILE_PROP,    C_YELLOW,      "币", "幸运金币(被动)" },
	/*  80    */ { TILE_PROP,    C_GREEN,       "圣", "圣水" },
	/*  81    */ { TILE_PROP,    C_BLUE,        "匕", "屠龙匕首" },
	/*  82    */ { TILE_PROP,    C_BLUE,        "记", "记事本" },
	/*  83-100 */
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },

	/* 101 */ { TILE_MONSTER, C_GREEN,  "⊙", "绿史莱姆" },
	/* 102 */ { TILE_MONSTER, C_RED,    "⊙", "红史莱姆" },
	/* 103 */ { TILE_MONSTER, C_PURPLE, "蝠", "小蝙蝠" },
	/* 104 */ { TILE_MONSTER, C_PURPLE, "法", "初级法师" },
	/* 105 */ { TILE_MONSTER, C_WHITE,  "骷", "骷髅" },
	/* 106 */ { TILE_MONSTER, C_BLUE,   "骷", "骷髅士兵" },
	/* 107 */ { TILE_MONSTER, C_YELLOW, "卫", "初级卫兵" },
	/* 108 */ { TILE_MONSTER, C_RED,    "骷", "骷髅队长" },
	/* 109 */ { TILE_MONSTER, C_PURPLE, "⊙", "大史莱姆" },
	/* 110 */ { TILE_MONSTER, C_RED,    "蝠", "大蝙蝠" },
	/* 111 */ { TILE_MONSTER, C_RED,    "法", "高级法师" },
	/* 112 */ { TILE_MONSTER, C_YELLOW, "兽", "兽人" },
	/* 113 */ { TILE_MONSTER, C_RED,    "兽", "兽人武士" },
	/* 114 */ { TILE_MONSTER, C_RED,    "石", "石头人" },
	/* 115 */ { TILE_MONSTER, C_RED,    "章", "巨型章鱼" },
	/* 116 */ { TILE_MONSTER, C_RED,    "血", "吸血鬼" },
	/* 117 */ { TILE_MONSTER, C_RED,    "师", "大法师" },
	/* 118 */ { TILE_MONSTER, C_BLUE,   "鬼", "鬼战士" },
	/* 119 */ { TILE_MONSTER, C_BLUE,   "战", "战士" },
	/* 120 */ { TILE_MONSTER, C_GREEN,  "幽", "幽灵" },
	/* 121 */ { TILE_MONSTER, C_BLUE,   "卫", "中级卫兵" },
	/* 122 */ { TILE_MONSTER, C_YELLOW, "武", "双手剑士" },
	/* 123 */ { TILE_MONSTER, C_RED,    "龙", "魔龙" },
	/* 124 */ { TILE_MONSTER, C_RED,    "骑", "骑士" },
	/* 125 */ { TILE_MONSTER, C_YELLOW, "骑", "骑士队长" },
	/* 126 */ { TILE_MONSTER, C_YELLOW, "巫", "初级巫师" },
	/* 127 */ { TILE_MONSTER, C_RED,    "巫", "高级巫师" },
	/* 128 */ { TILE_MONSTER, C_GREEN,  "Θ", "史莱姆王" },
	/* 129 */ { TILE_MONSTER, C_RED,    "蝠", "吸血蝙蝠" },
	/* 130 */ { TILE_MONSTER, C_PURPLE, "骑", "黑暗骑士" },
	/* 131 */ { TILE_MONSTER, C_BLUE,   "警", "魔法警卫" },
	/* 132 */ { TILE_MONSTER, C_RED,    "卫", "高级卫兵" },
	/* 133 */ { TILE_MONSTER, C_RED,    "王", "魔王" },
	/* 134 */ { TILE_MONSTER, C_RED,    "王", "魔王" },
	/* 135 */ { TILE_MONSTER, C_RED,    "王", "魔王" },
	/* 136 */ { TILE_MONSTER, C_RED,    "巫", "高级巫师" },
	/* 137 */ { TILE_MONSTER, C_BLUE,   "战", "战士(先攻)" },
	/* 138 */ { TILE_MONSTER, C_RED,    "骑", "骑士(先攻)" },
	/* 139 */ { TILE_MONSTER, C_BLUE,   "鬼", "鬼战士(先攻)" },
	/* 140 */ { TILE_OBJECT, C_WHITE,   "", "隐形墙" },
	/* 141 */ { TILE_MONSTER, C_YELLOW, "武", "双手剑士(先攻)" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" },

	/* 151 */ { TILE_NPC,     C_WHITE,  "老", "老人" },
	/* 152 */ { TILE_NPC,     C_RED,    "商", "商人" },
	/* 153 */ { TILE_NPC,     C_PURPLE, "公", "公主" },
	/* 154 */ { TILE_NPC,     C_YELLOW, "偷", "小偷" },
	/* 155 */ { TILE_NPC,     C_PURPLE, "祭", "祭坛" },

	/* 156 */ { TILE_OBJECT, C_RED, "", "怪物身躯" },
	/* 157-254 */
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },
	{ TILE_NONE, C_WHITE, "", "" }, { TILE_NONE, C_WHITE, "", "" },

	/* 255 (player) */
	{ TILE_NONE,    C_BLUE,  "勇", "勇者" },
};
